name: growgreen
description: Agroforestry Simulation Game
publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  lottie: ^3.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.5
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  logger: ^2.0.2+1
  firebase_auth: ^4.17.0
  gap: ^3.0.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  flame: ^1.14.0
  flame_tiled: ^1.18.3
  intl: ^0.19.0
  cloud_firestore: ^4.14.0
  synchronized: ^3.1.0+1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  uuid: ^4.2.2
  macos_window_utils: ^1.5.0
  fl_chart: ^0.66.2
  flame_audio: ^2.10.0
  shared_preferences: ^2.2.2
  app_links: ^3.5.1
  share_plus: ^7.2.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # map
    - assets/images/

    # animations (coin, river)
    - assets/images/animations/coins/
    - assets/images/animations/river/1/
    - assets/images/animations/river/2/
    - assets/images/animations/river/3/
    - assets/images/animations/river/4/
    - assets/images/animations/river/5/

    # clouds
    - assets/images/clouds/  

    # crop assets
    - assets/images/crops/bajra/
    - assets/images/crops/banana/
    - assets/images/crops/groundnut/
    - assets/images/crops/maize/
    - assets/images/crops/pepper/
    - assets/images/crops/wheat/

    # props
    - assets/images/props/

    # tiles
    - assets/images/tiles/

    # tree assets
    - assets/images/trees/coconut/
    - assets/images/trees/jackfruit/
    - assets/images/trees/mahagony/
    - assets/images/trees/mango/
    - assets/images/trees/neem/
    - assets/images/trees/rosewood/
    - assets/images/trees/teakwood/

    # game UI support assets
    - assets/game_assets/

    # game audio
    - assets/audio/
    - assets/audio/sfx/

  # Dentisity  Flutter pixel ratio
  # ldpi        0.75x
  # mdpi        1.0x
  # hdpi        1.5x
  # xhdpi       2.0x
  # xxhdpi      3.0x
  # xxxhdpi     4.0x

  fonts:
    - family: Lapsus Pro
      fonts:
        - asset: assets/fonts/lapsuspro.otf
