name: growgreen
description: Agroforestry Simulation Game
publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  logger: ^2.0.2+1
  firebase_auth: ^4.16.0
  gap: ^3.0.1
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  flame: ^1.14.0
  flame_tiled: ^1.18.3
  intl: ^0.19.0
  bot_toast: ^4.1.3
  cloud_firestore: ^4.14.0
  synchronized: ^3.1.0+1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/trees/
    - assets/images/crops/
    - assets/images/props/
    - assets/images/animations/
    - assets/images/animations/coins/
    - assets/images/tiles/
    - assets/images/clouds/
    - assets/exp/
    
    

  fonts:
    - family: Pina Colada Creation
      fonts:
        - asset: assets/fonts/Pina Colada Creation.ttf

