// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5eN3ztrQChZEGvLuqtrzLeAMwl8wl6ro',
    appId: '1:1008482153863:web:a349b9270ff1aed4c6cf22',
    messagingSenderId: '1008482153863',
    projectId: 'growgreen-8468f',
    authDomain: 'growgreen-8468f.firebaseapp.com',
    storageBucket: 'growgreen-8468f.appspot.com',
    measurementId: 'G-0YZR62SPMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcyKzZeCQCf7g6B7mSJQy7H5zMNb877Mg',
    appId: '1:1008482153863:android:3016d483416a21dfc6cf22',
    messagingSenderId: '1008482153863',
    projectId: 'growgreen-8468f',
    storageBucket: 'growgreen-8468f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeNeYLwCSkx1syyAE4Q0w8r3uSf7UkSw8',
    appId: '1:1008482153863:ios:212e60c85431c6f5c6cf22',
    messagingSenderId: '1008482153863',
    projectId: 'growgreen-8468f',
    storageBucket: 'growgreen-8468f.appspot.com',
    iosClientId: '1008482153863-rilf6gdm3gu0ppdlijm8d0do7l02f91k.apps.googleusercontent.com',
    iosBundleId: 'art.brainstorm.growgreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeNeYLwCSkx1syyAE4Q0w8r3uSf7UkSw8',
    appId: '1:1008482153863:ios:9b4cff0b3c5cac59c6cf22',
    messagingSenderId: '1008482153863',
    projectId: 'growgreen-8468f',
    storageBucket: 'growgreen-8468f.appspot.com',
    iosClientId: '1008482153863-nn9d76u2fh50rv067pohmhpitthjtad0.apps.googleusercontent.com',
    iosBundleId: 'art.brainstorm.growgreen.RunnerTests',
  );
}
